Support Mobile Identity Connect
Kinvey/nativescript-sdk pull request #1
Opened 2017-05-24 20:19 UTC by thomasconner

#### Description
This PR adds support for MIC to the SDK.

#### Changes
- Override User class to handle redirect on iOS
- Utilize [nativescript-advanced-webview](https://github.com/bradmartin/nativescript-advanced-webview) to show web view.

2017-06-08 20:40 UTC, tejasranade requested changes

2017-06-08 20:40 UTC, tejasranade commented on package.json
> +    "kinvey-js-sdk": "file:///Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/Core/SDK"
@thomasconner needs to point to npm module `js-sdk`

2017-06-08 20:40 UTC, tejasranade commented on src/middleware/src/cache.js
> +"use strict";
@thomasconner just a reminder to clean these compiled versions from the repo :)

2017-06-08 20:40 UTC, tejasranade commented on src/middleware/src/http.ts
> +  const parts = ['js-kinvey-nativescript-sdk/3.5.0'];
@thomasconner this needs to use the package name and number dynamically.

2017-06-08 20:40 UTC, tejasranade commented on src/middleware/src/http.ts
> +    return HttpRequest({
@thomasconner nothing wrong with this, but I'm curious why xhr didn't work. Can you try to find out? Afaik, xhr should work just fine.

2017-06-09 13:38 UTC, thomasconner commented on src/middleware/src/http.ts
> +  const parts = ['js-kinvey-nativescript-sdk/3.5.0'];
This is fixed in the other PR

2017-06-09 13:38 UTC, thomasconner commented on src/middleware/src/cache.js
> +"use strict";
This is fixed in #2

2017-06-09 13:41 UTC, thomasconner commented on package.json
> +    "kinvey-js-sdk": "file:///Users/Thomas/Documents/Kinvey/Development/SDKs/JavaScript/Core/SDK"
Fixed

2017-06-09 14:02 UTC, merged